name: Release

on:
  push:
    tags: ['*']

jobs:
  build-dist:
    runs-on: ${{ matrix.os }}
    env:
      CIBW_SKIP: cp3*-win* *-i686 cp36-* cp37-* pp36-* pp37-*
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            skip: '*-macos*'
            archs_linux: 'x86_64'
            archs_macos: ''
          - os: macos-latest
            skip: '*-linux*'
            archs_linux: ''
            archs_macos: 'arm64'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install cibuildwheel build

      - name: Build wheels
        env:
          CIBW_SKIP: ${{ env.CIBW_SKIP }} ${{ matrix.skip }}
          CIBW_ARCHS_LINUX: ${{ matrix.archs_linux }}
          CIBW_ARCHS_MACOS: ${{ matrix.archs_macos }}
        run: cibuildwheel --output-dir dist

      - name: Build sdist
        if: matrix.os == 'ubuntu-latest'
        run: python -m build --sdist --outdir dist

      - name: Upload dist-${{ matrix.os }}
        uses: actions/upload-artifact
        with:
          name: dist-${{ matrix.os }}
          path: dist

  publish:
    needs: build-dist
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download all dists
        uses: actions/download-artifact
        with:
          path: dist

      - name: Publish to PyPI    
        uses: pypa/gh-action-pypi-publish@release/v1